### PR TITLE
[Feat #6]: Create cart page

### PR DESCRIPTION
**Pull request by SanketDhabarde**
Screenshot (129)

### CODE REVIEW

**Review by maitrakhatri — APPROVED** [review]
looks good to me. Just make the place order button a button, right now it looks like a link

**Comment by SanketDhabarde** [comment]
> looks good to me. Just make the place order button a button, right now it looks like a link

On hover I put styles. Please tell me if it looks good or I will change to the button.
Screenshot (131)

**Review by aniketsingh13 — APPROVED** [review]
look good to me. just wanted to know why you use flex in card CSS. why not use utility

**Comment by SanketDhabarde** [comment]
> look good to me. just wanted to know why you use flex in card CSS. why not use utility

The reason for that is it is not fixed for eg. sometimes I need `justify-content: center`, sometimes `flex-start`, `flex-end`. That's why I thought why to write class for every property. it will be a lot of time-consuming. But I can do that if time permits. 

Thanks for pointing it out.

**Pull request merged**
